### ISSUE TITLE
Checkout vs Cart APIs

### ISSUE THREAD

**Issue by idank** [Flag-Nor-Fail/nuxt-storefront#1]
Hey, this is nicely structured and as a newcomer to Vue/Nuxt it's quite helpful to learn!

Curious why you're using the Cart Storefront API as opposed to Checkout? The latter is available in https://shopify.github.io/js-buy-sdk/ which exposes most of the APIs you've written.

**Comment by joshistoast** [comment]
No particular reason, haven't really touched the `checkout` aspect of the storefront api since `cart` has always worked fine for most all my use cases
Always open to PRs or suggestions if you feel like using `checkout` would be better!

**Comment by idank** [comment]
I ended up using cart too, can't really tell the difference. ^_^
